baseURL = 'https://jfex.art/'
title = 'jfexart'
theme = 'risotto'
author = 'Jorge Salazar Tovar'
copyright = "© 2023 | Jorge Salazar Tovar"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true
paginate = 5


[params.theme]
palette = "thimbleweed-dark"

[params.about]
title = "jfexart"
description = "the signals are strong tonight"
logo = "images/signal.png"


[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/jfexart"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/jfexart"

[[params.socialLinks]]
icon = "fa-brands fa-mastodon"
title = "Mastodon"
url = "https://mastodon.social/@jfexart/"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:me@jfex.art"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

    [[menu.main]]
    name = 'posts'
    pageRef = '/post'
    weight = 20

#    [[menu.main]]
#    name = 'topics'
#    pageRef = '/tags'
#    weight = 30

    [[menu.main]]
    name = 'projects'
    pageRef = '/project'
    weight = 40

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

    